name = "moontv-plus"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

# 静态资源配置
# Cloudflare Workers Assets 用于服务静态文件
[assets]
directory = ".open-next/assets"
binding = "ASSETS"


# 环境变量配置
# 所有变量统一在此管理，避免每次部署被覆盖
[vars]
NODE_ENV = "production"
BUILD_TARGET = "cloudflare"
USERNAME = "star"
PASSWORD = "boyu123456789"
NEXT_PUBLIC_DISABLE_YELLOW_FILTER = "true"
NEXT_PUBLIC_STORAGE_TYPE = "upstash"
UPSTASH_URL = "https://saved-crow-43905.upstash.io"
UPSTASH_TOKEN = "AauBAAIncDI4ZmYxMzI4YjI1ZDE0ZGI1YTAyMTc3ODY2Nzg3NmJmNnAyNDM5MDU"
